#spring.application.name=gateway
#server.port=8082
#
#logging.level.root=debug
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://admin:1234@localhost:8761/eureka,http://admin:1234@localhost:8762/eureka
#eureka.instance.prefer-ip-address=true
#
#management.endpoints.web.exposure.include=health,info
#
#spring.jwt.secret = "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

server:
  shutdown: graceful


spring:
  application:
    name: gateway
  profiles:
    active: prod
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

  cloud:
    gateway:
      routes:
        - id: authentication-api
          uri: lb://AUTHENTICATION-API
          predicates:
            - Path=/api/auth/**

        - id: coupon-api
          uri: lb://COUPON-API
          predicates: #사용자 쿠폰 목록 리스트(List<UserCouponDTO>), 결제창에서 사용가능 쿠폰 목록명(List<String>)
            - Path=/api/coupon/**
          filters:
            - name: JwtAuthorizationHeaderFilter
              args:
                secretKey: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

        - id: shop-api
          uri: lb://SHOP-API
          predicates:
            - Path=/api/cart/**, /api/users/**, /api/books/**, /api/points/**, /api/categories/**, /api/tags/**, /api/addresses/**, /api/order/**, /api/admin/order/**
          filters:
            - name: JwtAuthorizationHeaderFilter
              args:
                secretKey: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
